export const ADD_TO_CART ='ADD_TO_CARD';
export const CHANGE_MESSAGE ='CHANGE_MESSAGE';
export const UPDATE_PRODUCT_INCART ='UPDATE_PRODUCT_INCART';
export const DELETE_PRODUCT_IN_CART ='DELETE_PRODUCT_IN_CART';